//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERMs.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class BR_BriefingDiary
    {
        public int ID { get; set; }
        public System.DateTime Ngay { get; set; }
        public string manv { get; set; }
        public string ten { get; set; }
        public string hoten { get; set; }
        public string bophan { get; set; }
        public string chuyenbay { get; set; }
        public string noidung { get; set; }
        public int hinhthuc { get; set; }
        public string hinhthuc1 { get; set; }
        public string hinhthuc2 { get; set; }
        public string hinhthuc3 { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public int Status { get; set; }
        public string Base { get; set; }
        public string hinhthuc4 { get; set; }
    }
}
