//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERMs.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CR_Airplane_Crew
    {
        public int ID { get; set; }
        public Nullable<int> Prior { get; set; }
        public string Aircraft { get; set; }
        public string Routing { get; set; }
        public Nullable<int> P { get; set; }
        public Nullable<int> X { get; set; }
        public Nullable<int> B { get; set; }
        public Nullable<int> Y { get; set; }
        public string Note { get; set; }
        public Nullable<System.DateTime> Expired { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
        public string Creator { get; set; }
        public string Modifier { get; set; }
        public string Creatorid { get; set; }
        public string Modifierid { get; set; }
    }
}
