//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERMs.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CR_Flight_FinalReport_Replied_Log
    {
        public int ID { get; set; }
        public int FinalReportID { get; set; }
        public string Category { get; set; }
        public Nullable<int> Emergency { get; set; }
        public string Replierid { get; set; }
        public string Replier { get; set; }
        public Nullable<System.DateTime> Replied { get; set; }
        public string ReplyInfo { get; set; }
    }
}
