//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERMs.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CR_OJT_Lesson_Item
    {
        public int ID { get; set; }
        public Nullable<int> CR_OJT_Lesson_ID { get; set; }
        public int SN { get; set; }
        public string index { get; set; }
        public Nullable<bool> input { get; set; }
        public string Question { get; set; }
        public Nullable<int> Factor { get; set; }
        public string TextColor { get; set; }
        public string ScoreType { get; set; }
        public Nullable<int> Version { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
        public string Creator { get; set; }
        public string Modifier { get; set; }
        public string Creatorid { get; set; }
        public string Modifierid { get; set; }
    }
}
