//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERMs.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CR_Survey_Item
    {
        public int ID { get; set; }
        public Nullable<int> CR_Survey_ID { get; set; }
        public Nullable<bool> Input { get; set; }
        public string Question { get; set; }
        public Nullable<int> Factor { get; set; }
        public string Score { get; set; }
        public Nullable<int> ScoreValue { get; set; }
        public string Remark { get; set; }
        public string Comment { get; set; }
        public string TextColor { get; set; }
        public string ScoreType { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
        public string Creator { get; set; }
        public string Modifier { get; set; }
        public string Creatorid { get; set; }
        public string Modifierid { get; set; }
        public int SN { get; set; }
    
        public virtual CR_Survey CR_Survey { get; set; }
    }
}
