//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERMs.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CR_Survey
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CR_Survey()
        {
            this.CR_Survey_Item = new HashSet<CR_Survey_Item>();
        }
    
        public int ID { get; set; }
        public Nullable<int> FlightID { get; set; }
        public string FltInfo { get; set; }
        public string CID { get; set; }
        public string FullName { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string SeatNo { get; set; }
        public string PurserID { get; set; }
        public string PurserName { get; set; }
        public string LeaderID { get; set; }
        public string LeaderName { get; set; }
        public Nullable<int> CR_Survey_Category_ID { get; set; }
        public string CR_Survey_Category { get; set; }
        public Nullable<double> TotalScore { get; set; }
        public string Comment { get; set; }
        public string Suggestion { get; set; }
        public Nullable<System.DateTime> Signed { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
        public string Creator { get; set; }
        public string Modifier { get; set; }
        public string Creatorid { get; set; }
        public string Modifierid { get; set; }
        public Nullable<int> Type { get; set; }
        public string SurveyBy { get; set; }
        public string SignedBy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CR_Survey_Item> CR_Survey_Item { get; set; }
    }
}
