//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERMs.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class EM_Message
    {
        public int ID { get; set; }
        public Nullable<int> ParentID { get; set; }
        public string Source { get; set; }
        public string SenderID { get; set; }
        public string Sender { get; set; }
        public string ReceiverID { get; set; }
        public string Receiver { get; set; }
        public string PhoneNo { get; set; }
        public int Group { get; set; }
        public string Message { get; set; }
        public Nullable<int> Attachments { get; set; }
        public string Note { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<bool> Read { get; set; }
        public Nullable<System.DateTime> Readtime { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public string Creatorid { get; set; }
        public string Creator { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
        public string Modifierid { get; set; }
        public string Modifier { get; set; }
        public string OutboxNo { get; set; }
        public string SmsType { get; set; }
        public string SmsContent { get; set; }
        public Nullable<System.DateTime> SmsTimeOut { get; set; }
        public string ResultOut { get; set; }
        public Nullable<System.DateTime> SmsServerTime { get; set; }
        public Nullable<System.DateTime> SmsDeliveredTime { get; set; }
        public Nullable<System.DateTime> SmsCenterTime { get; set; }
        public Nullable<bool> SmsDelete { get; set; }
        public Nullable<bool> ReportStatus { get; set; }
        public string sSender { get; set; }
        public string sReader { get; set; }
        public Nullable<System.DateTime> dReadAt { get; set; }
        public Nullable<bool> bReplied { get; set; }
        public string sDeletedUser { get; set; }
        public Nullable<System.DateTime> dDeletedDate { get; set; }
        public Nullable<int> Priority { get; set; }
        public string Powerby { get; set; }
        public bool Notify { get; set; }
        public Nullable<System.DateTime> NotifyDate { get; set; }
        public string NoticeTitle { get; set; }
        public string Players { get; set; }
        public bool isHtml { get; set; }
        public int Newsid { get; set; }
        public Nullable<bool> SendtoSMS { get; set; }
    }
}
