//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERMs.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PView_giadinh1
    {
        public string mans { get; set; }
        public int loains { get; set; }
        public string loainhansu { get; set; }
        public Nullable<int> loaiquanhe { get; set; }
        public string quanhe { get; set; }
        public string hoten { get; set; }
        public System.DateTime ngaysinh { get; set; }
        public string cmnd_so { get; set; }
        public int bophanlamviec { get; set; }
        public string bophan { get; set; }
        public Nullable<System.DateTime> bienche_ngay { get; set; }
        public Nullable<System.DateTime> bienche_tct { get; set; }
        public Nullable<System.DateTime> bienche_dtv { get; set; }
        public Nullable<bool> nghiviec { get; set; }
        public Nullable<int> giadinhid { get; set; }
        public string Firstname { get; set; }
    }
}
