//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERMs.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecruitmentCandidate
    {
        public int Id { get; set; }
        public Nullable<int> CandidateType { get; set; }
        public string CandidateTypeText { get; set; }
        public Nullable<int> KnowledgeInfoBy { get; set; }
        public string KnowledgeInfoByText { get; set; }
        public Nullable<int> TestPlace { get; set; }
        public string TestPlaceText { get; set; }
        public Nullable<int> TestLanguage { get; set; }
        public string TestLanguageText { get; set; }
        public Nullable<int> TestNo { get; set; }
        public Nullable<int> TestedPlace { get; set; }
        public string TestedPlaceText { get; set; }
        public Nullable<System.DateTime> TestedDate { get; set; }
        public string FullName { get; set; }
        public Nullable<bool> Gender { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string PlaceOfOrigin { get; set; }
        public string IdentityOrPassportNo { get; set; }
        public Nullable<System.DateTime> IssueDate { get; set; }
        public string IssuePlace { get; set; }
        public string Address { get; set; }
        public string Phone1 { get; set; }
        public string Phone2 { get; set; }
        public string Email { get; set; }
        public Nullable<int> EducationLevel { get; set; }
        public string EducationLevelText { get; set; }
        public Nullable<int> ForeignLanguageLevel { get; set; }
        public string ForeignLanguageLevelText { get; set; }
        public Nullable<System.DateTime> ForeignLanguageTestedDate { get; set; }
        public Nullable<double> ForeignLanguageTestedPoint { get; set; }
        public string ForeignLanguageOther { get; set; }
        public string Gifted { get; set; }
        public string PastCompany { get; set; }
        public Nullable<int> AttachmentID { get; set; }
        public string PrivateKey { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public string Creator { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
        public string Modifier { get; set; }
    }
}
