//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERMs.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sys_Device
    {
        public int ID { get; set; }
        public int AID { get; set; }
        public string CID { get; set; }
        public string PhoneNo { get; set; }
        public string UDID { get; set; }
        public string Keycode { get; set; }
        public string PushToken { get; set; }
        public string DeviceName { get; set; }
        public string DeviceType { get; set; }
        public string DeviceOS { get; set; }
        public string Manufacture { get; set; }
        public string OSType { get; set; }
        public Nullable<bool> IsNotify { get; set; }
        public Nullable<bool> MainDevice { get; set; }
        public Nullable<System.DateTime> LastLogin { get; set; }
        public string OTPCode { get; set; }
        public Nullable<System.DateTime> OTPDate { get; set; }
        public int OTPCount { get; set; }
        public int OTPFailures { get; set; }
        public Nullable<bool> Activate { get; set; }
        public string Description { get; set; }
        public string Note { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public string Creator { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
        public string Modifier { get; set; }
        public string Creatorid { get; set; }
        public string Modifierid { get; set; }
        public string AuthUDID { get; set; }
        public string QRCode { get; set; }
    }
}
