//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERMs.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sys_LoggedIn
    {
        public int ID { get; set; }
        public int AID { get; set; }
        public string CID { get; set; }
        public string PhoneNo { get; set; }
        public string QRCode { get; set; }
        public System.DateTime QRTime { get; set; }
        public Nullable<System.DateTime> Logged { get; set; }
        public string MAC { get; set; }
        public string IPv4 { get; set; }
        public string IPv6 { get; set; }
        public string DeviceName { get; set; }
        public string DeviceType { get; set; }
        public string DeviceOS { get; set; }
        public string Manufacture { get; set; }
        public string OSType { get; set; }
        public Nullable<bool> Activate { get; set; }
        public string Description { get; set; }
        public string Note { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public string Creator { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
        public string Modifier { get; set; }
        public string Creatorid { get; set; }
        public string Modifierid { get; set; }
        public string LocalUser { get; set; }
        public string UDID { get; set; }
    }
}
