//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERMs.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket_Employee
    {
        public int ID { get; set; }
        public string CID { get; set; }
        public Nullable<int> EmployeeTypeID { get; set; }
        public string EmployeeType { get; set; }
        public Nullable<int> FamilyID { get; set; }
        public string Fullname { get; set; }
        public Nullable<int> RelationshipID { get; set; }
        public string Relationship { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public string PID { get; set; }
        public string DepartmentID { get; set; }
        public string Department { get; set; }
        public Nullable<bool> Retired { get; set; }
        public Nullable<int> Seniority { get; set; }
        public Nullable<System.DateTime> WorkStartDate { get; set; }
        public string JobTitle { get; set; }
        public Nullable<int> Version { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
        public string Creator { get; set; }
        public string Modifier { get; set; }
        public string Creatorid { get; set; }
        public string Modifierid { get; set; }
        public string FirstName { get; set; }
    }
}
