//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERMs.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket_Booking
    {
        public int ID { get; set; }
        public Nullable<bool> Pending { get; set; }
        public string ResCode { get; set; }
        public string TicketNo { get; set; }
        public string CID { get; set; }
        public string Passenger { get; set; }
        public string FlightNo { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Routing { get; set; }
        public string FltNote { get; set; }
        public Nullable<System.DateTime> IssueDate { get; set; }
        public string SitaAddress { get; set; }
        public Nullable<int> Status { get; set; }
        public string SabreStatus { get; set; }
        public string SabRequest { get; set; }
        public string SabResponse { get; set; }
        public Nullable<System.DateTime> SabDate { get; set; }
        public string SabFlightNo { get; set; }
        public string SabRouting { get; set; }
        public Nullable<System.DateTime> SabDepartdate { get; set; }
        public Nullable<System.DateTime> SabIssueDate { get; set; }
        public string Remark { get; set; }
        public string Note { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
        public string Creator { get; set; }
        public string Modifier { get; set; }
        public string Creatorid { get; set; }
        public string Modifierid { get; set; }
    }
}
