//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERMs.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TourRegister2018
    {
        public int ID { get; set; }
        public int IDTour { get; set; }
        public string Mail { get; set; }
        public string MSNV { get; set; }
        public string HoTen { get; set; }
        public string QuanHe { get; set; }
        public string CMND { get; set; }
        public string NgaySinh { get; set; }
        public bool AnThongTin { get; set; }
        public Nullable<System.DateTime> NgayCapNhat { get; set; }
        public string NguoiCapNhat { get; set; }
        public Nullable<int> TinhTrang { get; set; }
        public bool IsDelete { get; set; }
    }
}
