//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication1.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class CR_Dbf_lbmb
    {
        public int ID { get; set; }
        public string Codefly { get; set; }
        public string CodeApl { get; set; }
        public string TypeApl { get; set; }
        public string Acf { get; set; }
        public string FlightNo { get; set; }
        public string Leg { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public string StartTime { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string EndTime { get; set; }
        public string AcfNo { get; set; }
        public string Cfg { get; set; }
        public string Status { get; set; }
        public string Note { get; set; }
        public string Base { get; set; }
        public string UserNane { get; set; }
        public Nullable<System.DateTime> EditDate { get; set; }
        public string EditTime { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
        public string Creator { get; set; }
        public string Modifier { get; set; }
        public string Creatorid { get; set; }
        public string Modifierid { get; set; }
    }
}
