//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication1.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class CR_FlightInfo
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string FlightNo { get; set; }
        public string Routing { get; set; }
        public string Aircraft { get; set; }
        public string RegisterNo { get; set; }
        public Nullable<System.DateTime> UTC { get; set; }
        public Nullable<System.DateTime> Departed { get; set; }
        public Nullable<System.DateTime> Arrived { get; set; }
        public string Parking { get; set; }
        public string Gate { get; set; }
        public string TypeApl { get; set; }
        public string Acf { get; set; }
        public string AcfNo { get; set; }
        public Nullable<int> Status { get; set; }
        public string Note { get; set; }
        public string Carry { get; set; }
        public Nullable<int> PaxC { get; set; }
        public Nullable<int> PaxI { get; set; }
        public Nullable<int> PaxY { get; set; }
        public Nullable<int> VIP { get; set; }
        public Nullable<int> CIP { get; set; }
        public string PaxBooking { get; set; }
        public string PaxClosed { get; set; }
        public Nullable<int> Wchr { get; set; }
        public Nullable<int> SM { get; set; }
        public Nullable<int> BSCT { get; set; }
        public Nullable<int> INF { get; set; }
        public Nullable<int> UM { get; set; }
        public Nullable<int> BLND { get; set; }
        public Nullable<int> DEAF { get; set; }
        public Nullable<int> STCR { get; set; }
        public Nullable<int> EXST { get; set; }
        public Nullable<int> DEPU { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
        public string Creator { get; set; }
        public string Modifier { get; set; }
        public string Creatorid { get; set; }
        public string Modifierid { get; set; }
    }
}
