//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication1.DataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ERMSEntities : DbContext
    {
        public ERMSEntities()
            : base("name=ERMSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CR_Dbf_lbmb> CR_Dbf_lbmb { get; set; }
        public virtual DbSet<CR_FlightInfo> CR_FlightInfo { get; set; }
        public virtual DbSet<ER_Employee> ER_Employee { get; set; }
        public virtual DbSet<Sys_SabreLoader> Sys_SabreLoader { get; set; }
    }
}
